using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitle("DotNetShipping")]
[assembly: AssemblyDescription("UPS, FedEx, USPS shipping rate calculators for .NET")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Kyle West")]
[assembly: AssemblyProduct("DotNetShipping")]
[assembly: AssemblyCopyright("Copyright (c) 2012 Kyle West")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: AssemblyVersion("0.5.2.10131")]
[assembly: AssemblyFileVersion("0.5.2.10131")]

